DROP TABLE comment;
DROP TABLE likes;
DROP TABLE post_tag;
DROP TABLE tag;
DROP TABLE post;

------------------------------------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS post (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name varchar(64) NOT NULL,
  image_url varchar(512) NOT NULL,
  description text[] NOT NULL,
  commentsCount INTEGER DEFAULT 0,
  CONSTRAINT pk_post_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tag (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name varchar(64) NOT NULL,
  CONSTRAINT pk_tag_id PRIMARY KEY (id),
  CONSTRAINT uk_tag_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS post_tag (
	post_id INTEGER,
	tag_id INTEGER,
	CONSTRAINT pk_post_tag_id PRIMARY KEY (post_id, tag_id),
	CONSTRAINT fk_post_tag_post_id FOREIGN KEY (post_id)
          REFERENCES post (id) ON DELETE CASCADE,
	CONSTRAINT fk_post_tag_tag_id FOREIGN KEY (tag_id)
          REFERENCES tag (id) --ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  count INTEGER NOT NULL,
  post_id INTEGER NOT NULL,
  CONSTRAINT pk_likes_id PRIMARY KEY (id),
  CONSTRAINT uk_likes_post_id UNIQUE (post_id),
  CONSTRAINT fk_likes_post_id FOREIGN KEY (post_id)
          REFERENCES post (id) ON DELETE CASCADE
); -- create index post_id, count ??? - UNIQUE (post_id) exists

CREATE TABLE IF NOT EXISTS comment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  post_comment varchar(2048),
  post_id INTEGER NOT NULL,
  CONSTRAINT pk_comment_id PRIMARY KEY (id),
  CONSTRAINT fk_comment_post_id FOREIGN KEY (post_id)
          REFERENCES post (id) ON DELETE CASCADE
);

------------------------------------------------------------------------------------------------------------------------
-- index for the tag-help quick search in posts
CREATE INDEX idx_post_tag_tag_id_post_id ON post_tag(tag_id, post_id);

-- index for the quick search comments to one post
CREATE INDEX idx_comment_post_id_post_comment ON comment(post_id, post_comment);
------------------------------------------------------------------------------------------------------------------------

INSERT INTO post (name, image_url, description, commentsCount)
VALUES
('Суп харчо', 'https://eda.ru/images/RecipePhoto/620x415/sup-harcho-s-adzhikoy_137460_photo_152843.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Овсянка', 'https://eda.ru/images/RecipePhoto/620x415/ovsyanka-na-zavtrak-s-yablokom-izyumom-i-medom_187506_photo_195300.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-22', 'description-23'], 0),
('Пицца по-американски', 'https://eda.ru/images/RecipePhoto/620x415/picca-po-amerikanski_15040_photo_6999.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-32', 'description-33'], 0),
('Лечо', 'https://eda.ru/images/RecipePhoto/620x415/lecho_28888_photo_44916.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-42', 'description-43'], 0),
('Суп с тефтелями', 'https://eda.ru/images/RecipePhoto/620x415/sup-s-tefteljami_34442_photo_21378.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Кулури', 'https://eda.ru/images/RecipePhoto/620x415/kuluri-klassicheskiy-grecheskiy-zavtrak_92811_photo_142705.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Салат «Панцанелла»', 'https://eda.ru/images/RecipePhoto/620x415/salat-pancanella_24450_photo_8845.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Грибы', 'https://eda.ru/images/RecipePhoto/620x415/gribi-na-zakusku_17164_photo_2194.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Паста с иваси', 'https://eda.ru/images/RecipePhoto/620x415/pasta-s-ivasi_125879_photo_149524.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Томатный суп', 'https://eda.ru/images/RecipePhoto/620x415/tomatnij-sup-s-krasnoj-fasolju-i-veshenkami_45718_photo_43334.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Французские гренки', 'https://eda.ru/images/RecipePhoto/620x415/francuzskie-grenki-k-zavtraku_32744_photo_16686.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Пибимпап', 'https://eda.ru/images/RecipePhoto/620x415/pibimpap-koreyskoe-blyudo_49883_photo_53669.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Фаршированные баклажаны', 'https://eda.ru/images/RecipePhoto/620x415/zakuska-iz-farshirovannih-baklazhanov_19141_photo_3792.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Русский салат', 'https://eda.ru/images/RecipePhoto/620x415/russkiy-salat_151817_photo_158462.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Чихиртма', 'https://eda.ru/images/RecipePhoto/620x415/chihirtma-iz-kuricy-po-domashnemu_140492_photo_156542.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Яйца-крэмбл', 'https://eda.ru/images/RecipePhoto/620x415/jajca-krjembl-k-zavtraku_50799_photo_55974.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Ризотто', 'https://eda.ru/images/RecipePhoto/620x415/rizotto_17052_photo_2092.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Тарталетки', 'https://eda.ru/images/RecipePhoto/620x415/tartaletki-s-vetchinno-sirnoj-zakuskoj_48029_photo_48909.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Салат нисуаз', 'https://eda.ru/images/RecipePhoto/620x415/salat-nisuaz-s-rukkoloj_25267_photo_9508.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 2),
('Сырники', 'https://eda.ru/images/RecipePhoto/620x415/sirniki-k-zavtraku_47166_photo_94332.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0),
('Манты', 'https://eda.ru/images/RecipePhoto/620x415/buuzi-tradicionnoe-burjatskoe-bljudo_42067_photo_34970.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 1),
('Блины', 'https://eda.ru/images/RecipePhoto/620x415/klassicheskie-bliny_140749_photo_158999.webp',
ARRAY['Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas ad sequi quidem at nostrum quos.', 'description-12', 'description-13'], 0)
ON CONFLICT DO NOTHING;

INSERT INTO tag (name)
VALUES
('#meat'),
('#chees'),
('#milk'),
('#rise')
ON CONFLICT DO NOTHING;

INSERT INTO post_tag (post_id, tag_id)
VALUES
(19, 1),
(21, 2),
(20, 3),
(19, 4),
(22, 3),
(19, 3)
ON CONFLICT DO NOTHING;

INSERT INTO likes (count, post_id)
VALUES
(1, 19),
(5, 20),
(4, 21)
ON CONFLICT DO NOTHING;

INSERT INTO comment (post_comment, post_id)
VALUES
('some-comment-11', 19),
('some-comment-12', 19),
('some-comment-31', 21)
ON CONFLICT DO NOTHING;

------------------------------------------------------------------------------------------------------------------------

-- create new post
CREATE OR REPLACE PROCEDURE create_new_post(IN post_name varchar, IN image_url varchar, IN description text[], IN tags_array varchar[])
LANGUAGE plpgsql
AS
'
DECLARE
  p_id INT;
  tags_id_arr int[];
BEGIN
  INSERT INTO post(name, image_url, description, commentsCount)
	VALUES
	(post_name, image_url, description, 0)
	ON CONFLICT DO NOTHING
	RETURNING id INTO p_id;

	INSERT INTO tag(name)
	VALUES (unnest(tags_array))
	ON CONFLICT DO NOTHING;

	SELECT ARRAY_AGG(t.id) FROM tag t WHERE name LIKE ANY(tags_array) INTO tags_id_arr;

	INSERT INTO post_tag
	VALUES
	(p_id, unnest(tags_id_arr));
END;'
;
------------------------------------------------------------------------------------------------------------------------

-- update post
CREATE OR REPLACE PROCEDURE update_post(IN update_post_id INTEGER, IN post_name varchar, IN post_image_url varchar, IN post_description text[], IN tags_array varchar[])
LANGUAGE plpgsql
AS
'
DECLARE
  tags_id_arr int[];
BEGIN
	UPDATE post
	SET
	name = post_name,
	image_url = post_image_url,
	description = post_description
	WHERE id = update_post_id;

	INSERT INTO tag(name)
	VALUES (unnest(tags_array))
	ON CONFLICT DO NOTHING;

	SELECT ARRAY_AGG(t.id) FROM tag t WHERE name LIKE ANY(tags_array) INTO tags_id_arr;

	DELETE FROM post_tag
	WHERE post_id = update_post_id
	AND tag_id <> ANY(tags_id_arr);

	INSERT INTO post_tag
	VALUES
	(update_post_id, unnest(tags_id_arr))
	ON CONFLICT DO NOTHING;
END;'
;

------------------------------------------------------------------------------------------------------------------------

--create table if not exists post(
--  id integer generated by default as identity,
--  name varchar(64) not null,
--  image_url varchar(512) not null,
--  description text array not null,
--  constraint pk_post_id primary key (id),
--  constraint uk_post_name unique (name)
--  );

--CREATE TABLE IF NOT EXISTS "POST" (
--  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
--  "NAME" varchar(64) NOT NULL,
--  "IMAGE_URL" varchar(512) NOT NULL,
--  -- "DESCRIPTION" varchar(192) NOT NULL,
----  "DESCRIPTION" text[] NOT NULL,
--  "DESCRIPTION" text ARRAY NOT NULL,
--  CONSTRAINT "PK_POST_ID" PRIMARY KEY ("ID"),
--  CONSTRAINT "UK_POST_NAME" UNIQUE ("NAME")
--);
--
--CREATE TABLE IF NOT EXISTS "TAG" (
--  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
--  "NAME" varchar(64) NOT NULL,
--  "POST_ID" INTEGER NOT NULL,
--  CONSTRAINT "PK_TAG_ID" PRIMARY KEY ("ID"),
--  CONSTRAINT uk_tag_name_post_id UNIQUE (name, post_id),
--  CONSTRAINT "FK_TAG_POST_ID" FOREIGN KEY ("POST_ID")
--          REFERENCES "POST" ("ID") ON DELETE CASCADE
--);
--
--CREATE TABLE IF NOT EXISTS "LIKES" (
--  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
--  "COUNT" INTEGER NOT NULL,
--  "POST_ID" INTEGER NOT NULL,
--  CONSTRAINT "PK_LIKES_ID" PRIMARY KEY ("ID"),
--  CONSTRAINT "FK_LIKES_POST_ID" FOREIGN KEY ("POST_ID")
--          REFERENCES "POST" ("ID") ON DELETE CASCADE
--);
--
--CREATE TABLE IF NOT EXISTS "COMMENT" (
--  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY,
--  "POST_COMMENT" varchar(1024),
--  "POST_ID" INTEGER NOT NULL,
--  CONSTRAINT "PK_COMMENT_ID" PRIMARY KEY ("ID"),
--  CONSTRAINT "FK_COMMENT_POST_ID" FOREIGN KEY ("POST_ID")
--          REFERENCES "POST" ("ID") ON DELETE CASCADE
--);
--
--INSERT INTO "POST" ("NAME", "IMAGE_URL", "DESCRIPTION")
--VALUES
--('Plov', 'url-1', '{description-11, description-12, description-13}'),
--('Pasta', 'url-2', '{description-21, description-22, description-23}'),
--('Pizza', 'url-3', '{description-31, description-32, description-33}')
--ON CONFLICT DO NOTHING;
--
--INSERT INTO "TAG" ("NAME", "POST_ID")
--VALUES
--('#meat', 1),
--('#chees', 3),
--('#mmm', 2),
--('#rise', 1)
--ON CONFLICT DO NOTHING;
--
--INSERT INTO "LIKES" ("COUNT", "POST_ID")
--VALUES
--(1, 1),
--(5, 2),
--(4, 3)
--ON CONFLICT DO NOTHING;
--
--INSERT INTO "COMMENT" ("POST_COMMENT", "POST_ID")
--VALUES
--('SOME_COMMENT-1', 1),
--('SOME_COMMENT-2', 1),
--('SOME_COMMENT-3', 3)
--ON CONFLICT DO NOTHING;
--
--INSERT INTO "POST" ("NAME", "IMAGE_URL", "DESCRIPTION")
--VALUES
--('Omelet', 'url-4', '{description-41, description-42, description-43}') ON CONFLICT DO NOTHING;

--DROP DATABASE blogdb;

--DO $$
--BEGIN
--    IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'blogdb') THEN
--        -- EXECUTE 'CREATE USER sa WITH PASSWORD \'password\'; ALTER USER sa WITH SUPERUSER; CREATE DATABASE blogdb WITH OWNER sa; GRANT ALL PRIVILEGES ON DATABASE blogdb to sa;';
--        EXECUTE 'CREATE DATABASE blogdb WITH OWNER serega'
--    END IF;
--END $$;


--DROP DATABASE blog;
--CREATE DATABASE blog WITH OWNER serega;

--CREATE DATABASE blog WITH OWNER serega;
--
--USE blog;
--
--create table if not exists tabletest(  -- WORK !!!
--  id integer ,
--  name varchar(64)
--  );


--CREATE ROLE sa WITH
--	LOGIN
--	SUPERUSER
--	CREATEDB
--	CREATEROLE
--	INHERIT
--	NOREPLICATION
--	CONNECTION LIMIT -1
--	PASSWORD 'password';

--DO $$
--BEGIN
--    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='sa') THEN
--        -- EXECUTE 'CREATE USER sa WITH PASSWORD \'password\'; ALTER USER sa WITH SUPERUSER; CREATE DATABASE blogdb WITH OWNER sa; GRANT ALL PRIVILEGES ON DATABASE blogdb to sa;';
--        EXECUTE 'CREATE USER sa WITH PASSWORD \'password\'';
--    END IF;
--END $$;

--CREATE TABLE IF NOT EXISTS post (
--  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--  name varchar(64) NOT NULL,
--  image_url varchar(512) NOT NULL,
--  description text[] NOT NULL,
--  CONSTRAINT pk_post_id PRIMARY KEY (id),
--  CONSTRAINT uk_post_name UNIQUE (name)
--);
-- "DESCRIPTION" varchar(192) NOT NULL,

--CREATE TABLE IF NOT EXISTS tag (
--  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--  name varchar(64) NOT NULL,
--  post_id INTEGER NOT NULL,
--  CONSTRAINT pk_tag_id PRIMARY KEY (id),
--  CONSTRAINT uk_tag_name_post_id UNIQUE (name, post_id)
--  CONSTRAINT fk_tag_post_id FOREIGN KEY (post_id)
--          REFERENCES post (id) ON DELETE CASCADE
--);
--
--CREATE TABLE IF NOT EXISTS likes (
--  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--  count INTEGER NOT NULL,
--  post_id INTEGER NOT NULL,
--  CONSTRAINT pk_likes_id PRIMARY KEY (id),
--  CONSTRAINT fk_likes_post_id FOREIGN KEY (post_id)
--          REFERENCES post (id) ON DELETE CASCADE
--);
--
--CREATE TABLE IF NOT EXISTS comment (
--  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
--  post_comment varchar(2048),
--  post_id INTEGER NOT NULL,
--  CONSTRAINT pk_comment_id PRIMARY KEY (id),
--  CONSTRAINT fk_comment_post_id FOREIGN KEY (post_id)
--          REFERENCES post (id) ON DELETE CASCADE
--);
--
--INSERT INTO post (name, image_url, description)
--VALUES
--('Plov', 'url-1', '{description-11, description-12, description-13}'),
--('Pasta', 'url-2', '{description-21, description-22, description-23}'),
--('Pizza', 'url-3', '{description-31, description-32, description-33}'),
--('Omelet', 'url-4', '{description-41, description-42, description-43}')
--ON CONFLICT DO NOTHING;
--
--
--INSERT INTO tag (name, post_id)
--VALUES
--('#meat', 1),
--('#chees', 3),
--('#mmm', 2),
--('#rise', 1)
--ON CONFLICT DO NOTHING;
--
--INSERT INTO likes (count, post_id)
--VALUES
--(1, 1),
--(5, 2),
--(4, 3)
--ON CONFLICT DO NOTHING;
--
--INSERT INTO comment (post_comment, post_id)
--VALUES
--('some-comment', 1),
--('some-comment', 1),
--('some-comment', 3)
--ON CONFLICT DO NOTHING;


