#spring.datasource.url=jdbc:h2:mem:blogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.url=jdbc:postgresql://localhost:5432/blog
#spring.sql.init.mode=always
spring.batch.initialize-schema=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=serega
spring.datasource.password=escort
